api/urls.py
from rest_framework import routers

from api.posts.views import CategoryApiView
from api.front.views import WhatColorizeApiView
from api.comments.views import CommentsView

app_name = 'api'


router = routers.DefaultRouter()

router.register(r'what_colorize', WhatColorizeApiView, 'what_colorize')
router.register(r'category', CategoryApiView, 'category')
router.register(r'comments', CommentsView, 'comments')

urlpatterns = router.urls

front/urls.py
from django.urls import path

from front.views import Home, FeedBack, TermsOfUse,\
    RightHolders, Sitemap, CookieRules, WhatRegister, WhatColorize


app_name = 'front'

urlpatterns = [
    path('', Home.as_view(), name='home'),
    path('terms-of-use/', TermsOfUse.as_view(), name='terms_of_use'),
    path('feedback/', FeedBack.as_view(), name='feedback'),
    path('what-register/', WhatRegister.as_view(), name='what_register'),
    path('right-holders/', RightHolders.as_view(), name='right_holders'),
    path('cookie_rules/', CookieRules.as_view(), name='cookie_rules'),
    path('sitemap/', Sitemap.as_view(), name='sitemap'),
    path('what_colorize/', WhatColorize.as_view(), name='what_colorize'),
]

posts/urls.py
from django.urls import path
from posts.views import Category, Post, post_like,\
    post_add_wishlist, post_remove_wishlist, SearchPosts


app_name = 'posts'

urlpatterns = [
    path('post_like/<int:pk>/', post_like, name='post_like'),
    path('post_add_wishlist/<int:pk>/', post_add_wishlist, name='post_add_wishlist'),
    path('post_remove_wishlist/<int:pk>/', post_remove_wishlist, name='post_remove_wishlist'),
    path('search/', SearchPosts.as_view(), name='search'),

    # Эти 2 роута всегда внизу! они все съедают
    path('<slug:slug>/', Category.as_view(), name="category"),
    path('srisovka/<slug:slug>/', Post.as_view(), name="post")
]

step_drawing/urls.py
from django.urls import path
from step_drawing.views import Home, CategoryOrPost, post_step_like


app_name = 'step_drawing'

urlpatterns = [
    path('', Home.as_view(), name='home'),
    path('post_step_like/<int:pk>/', post_step_like, name='post_step_like'),
    path('<slug:slug>/', CategoryOrPost.as_view(), name="category_or_post"),
    # path('post_add_wishlist/<int:pk>/', post_add_wishlist, name='post_add_wishlist'),
    # path('post_remove_wishlist/<int:pk>/', post_remove_wishlist, name='post_remove_wishlist'),
    # path('search/', SearchPosts.as_view(), name='search'),

    # # Эти 2 роута всегда внизу! они все съедают
    # path('<slug:slug>/', Category.as_view(), name="category"),
    # path('srisovka/<slug:slug>/', Post.as_view(), name="post")
]

users/urls.py
from django.urls import path
from users.views import Detail, Settings, Wishlist, UserAddPost

app_name = 'profile'


urlpatterns = [

    path('', Detail.as_view(), name='detail'),
    path('settings/', Settings.as_view(), name='settings'),
    path('wishlist/', Wishlist.as_view(), name='wishlist'),
    path('add_post/', UserAddPost.as_view(), name='add_post'),
]

posts/models.py
import os
from PIL import Image
from mptt.models import MPTTModel, TreeForeignKey, TreeManyToManyField
from ckeditor.fields import RichTextField
from imagekit.models import ImageSpecField
from imagekit.processors import ResizeToFill

from django.db import models
from django.urls import reverse
from django.conf import settings
from django.dispatch import receiver
from django.contrib.auth import get_user_model
from django.db.models.signals import pre_delete

from utils.file import get_extension
from utils.rand import get_random_number
from utils.text import translite_slug
from posts.managers import PostManager
from configs.models import PostConfiguration

User = get_user_model()


def image_path_category(instance, filename):
    return f'category/{str(instance.slug)}{get_extension(filename)}'

def image_main_path_category(instance, filename):
    return f'category/{str(instance.slug)}_main{get_extension(filename)}'

def image_menu_path_category(instance, filename):
    return f'category/{str(instance.slug)}_menu{get_extension(filename)}'


class Category(MPTTModel):

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    class MPTTMeta:
        order_insertion_by = ['position']

    def __str__(self):
        return self.name

    parent = TreeForeignKey('self', on_delete=models.CASCADE, null=True, blank=True, related_name='children')

    name = models.CharField(max_length=100, unique=True, verbose_name='Наименование')
    position = models.IntegerField(default=0, verbose_name='Позиция')
    enabled = models.BooleanField(default=False, choices=settings.STATUS_CHOICES,
        verbose_name='Включено', help_text='Отображать/неотображать категорию')
    text1 = RichTextField(null=True, blank=True, verbose_name='Текст 1')
    text2 = RichTextField(null=True, blank=True, verbose_name='Текст 2')

    h1 = models.CharField(max_length=250)
    title = models.CharField(max_length=250, default='Картинки для срисовки')
    slug = models.SlugField(max_length=100, unique=True, verbose_name='Url(slug)', help_text='Ссылка на категорию')
    description = models.TextField(null=True, blank=True)

    image = models.FileField(upload_to=image_path_category, null=True, blank=True,
        verbose_name='Основное изображение', help_text='Отображается в категории')
    image_menu = models.FileField(upload_to=image_menu_path_category, null=True, blank=True,
        verbose_name='Картинка в меню', help_text='Иконка в меню')
    show_main = models.BooleanField(default=False, verbose_name='Отображать на главной или нет')
    image_main = models.FileField(upload_to=image_main_path_category, null=True, blank=True,
        verbose_name='Картинка на главной', help_text='Отображается на главной')

    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Создано')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='Обновлено')

    def image_path(self):
        return f'{settings.MEDIA_URL}{self.image}'

    def image_menu_path(self):
        return f'{settings.MEDIA_URL}{self.image_menu}'

    def image_main_path(self):
        return f'{settings.MEDIA_URL}{self.image_main}'

    def get_alt(self):
        return f'Срисовки {self.name.lower()} - распечатать, скачать бесплатно'

    def get_title(self):
        return f'Срисовки {self.name.lower()}'

    def get_absolute_url(self):
        return reverse('posts:category', args=[str(self.slug)])


def image_path_post(instance, filename):
    '''Фомируем путь загрузки картинки'''
    return f'{get_path_img(instance)}{get_extension(filename)}'


def get_path_img(instance):
    '''
        Посты юзеров - posts_users/ имя юзера / пост слаг
        Посты админа - posts_admins/ майн категория / пост слаг
    '''
    if instance.user.is_staff or instance.user.is_superuser:
        return f'posts_admins/{translite_slug(str(instance.main_category.slug))}/{str(instance.slug)}'
    return f'posts_users/{translite_slug(str(instance.user))}/{str(instance.slug)}'


class Post(models.Model):

    objects = models.Manager()
    get = PostManager()

    class Meta:
        verbose_name = 'Запись'
        verbose_name_plural = 'Записи'
        ordering = ['-created_at']

    def __str__(self):
        '''Возвращаем h1'''
        if self.user.is_superuser or self.user.is_staff:
            return self.name
        return f'{self.name} - от {self.user}'

    wishlist = models.ManyToManyField(User)

    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name='posts')
    position = models.IntegerField(default=0, verbose_name='Позиция')
    enabled = models.BooleanField(
        default=False, choices=settings.STATUS_CHOICES,
        verbose_name='Опубликовано', help_text='Отображать/неотображать пост')
    categories = TreeManyToManyField(
        Category, verbose_name='Категории', related_name='posts_cat', blank=True)
    main_category = TreeForeignKey(
        Category, on_delete=models.CASCADE, null=True,
        verbose_name='Основная категория', related_name='posts_main',
        help_text='Используется для хлебных крошек')

    name = models.CharField(max_length=250, unique=True, verbose_name='h1', help_text='Название поста')
    slug = models.SlugField(max_length=100, unique=True, verbose_name='Url(slug)')
    title = models.CharField(max_length=250, default='Картинка для срисовки')
    description = models.TextField(null=True, blank=True)

    text = models.TextField(null=True, blank=True, verbose_name='Текст')

    image = models.ImageField(
        upload_to=image_path_post, verbose_name='Изображение',
        help_text='Ожидается изображение 800х800 jpeg')
    image_thumb_300 = ImageSpecField(
        source='image',
        processors=[ResizeToFill(300, 300)],
        format='JPEG', options={'quality': 65})
    image_thumb_200 = ImageSpecField(
        source='image',
        processors=[ResizeToFill(200, 200)],
        format='JPEG', options={'quality': 60})
    image_thumb_100 = ImageSpecField(
        source='image',
        processors=[ResizeToFill(100, 100)],
        format='JPEG', options={'quality': 60})

    like = models.IntegerField(default=0, verbose_name='Лайки', help_text='Общее количество лайков')
    click = models.IntegerField(default=0, verbose_name='Клики', help_text='Общее количество кликов')

    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Создано')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='Обновлено')

    def save(self, *args, **kwargs):
        if not self.id and (self.user.is_staff or self.user.is_superuser):
            self.like = get_random_number(0, 3)
            self.click = get_random_number(0, 6)
        super(Post, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('posts:post', args=[str(self.slug)])

    def image_path(self):
        return f'{settings.MEDIA_URL}{self.image}'

    def download_name(self):
        return f'{self.name.replace(" ", "_")}-картинки_для_срисовки_рф'

    def get_alt(self):
        if self.user.is_superuser or self.user.is_staff:
            return f'{self.name.lower()} - распечатать, скачать бесплатно'
        return f'{self.name} срисовал {self.user}'

    def get_title(self):
        if self.user.is_superuser or self.user.is_staff:
            return f'Срисовка {self.name.lower()}'
        return f'Срисовка {self.name.lower()} от {self.user}'


@receiver(pre_delete, sender=Category)
def cat_image_delete(sender, instance, **kwargs):
    '''Удаляем картинки с категории, при удалении категории'''
    if instance.image:
        instance.image.delete()
    if instance.image_main:
        instance.image_main.delete()
    if instance.image_menu:
        instance.image_menu.delete()


@receiver(pre_delete, sender=Post)
def post_image_delete(sender, instance, **kwargs):
    '''Удаляем картинки с поста, при удалении поста'''
    if instance.image:
        thumb_path = f'{settings.MEDIA_ROOT}/{get_path_img(instance)}'
        thumb_extension = get_extension(str(instance.image))
        try:
            os.remove(f'{thumb_path}_300{thumb_extension}')
        except FileNotFoundError:
            pass
        try:
            os.remove(f'{thumb_path}_200{thumb_extension}')
        except FileNotFoundError:
            pass
        try:
            os.remove(f'{thumb_path}_100{thumb_extension}')
        except FileNotFoundError:
            pass
        instance.image.delete()

api/posts/views.py
from rest_framework import mixins, viewsets
from rest_framework.permissions import AllowAny

from api.posts.serializers import CategorySerializer
from posts.models import Category


class CategoryApiView(mixins.ListModelMixin, viewsets.GenericViewSet):

    serializer_class = CategorySerializer

    def get_queryset(self):
        first_level = self.request.GET.get('first_level', None)
        if first_level:
            return Category.objects.filter(level=0)
        return Category.objects.all()

    def get_permissions(self):
        permission_classes = [AllowAny, ]
        return [permission() for permission in permission_classes]

posts/views.py
from django.http import JsonResponse, Http404
from django.db.models import Q
from django.shortcuts import render
from django.views.generic import View
from django.core.paginator import Paginator
from django.core.exceptions import ObjectDoesNotExist

from posts.models import Category as CategoryModel, Post as PostModel


class Category(View):

    template_name = 'category/category.html'

    first_page = 1
    posts_in_page = 34

    def get(self,request, slug):
        categories = CategoryModel.objects.filter(slug=slug).get_descendants(include_self=True)
        if categories:
            active_page = request.GET.get('page', self.first_page)
            posts = PostModel.objects.filter(categories__slug=slug, enabled=True).order_by('main_category__position', '-created_at')
            p = Paginator(posts, self.posts_in_page)
            page = p.page(active_page)
            context = {
                'category': categories.first(),
                'categories': categories,
                'posts': page.object_list,
                'page_range': p.page_range,
                'active_page': active_page,
                'page': page
            }
            return render(request, self.template_name, context)
        raise Http404()


class Post(View):

    template_name = 'post/post.html'

    def get(self, request, slug):
        try:
            post = PostModel.objects.get(slug=slug)
        except ObjectDoesNotExist:
            raise Http404()

        post.click = int(post.click) + 1
        post.save()

        some_next_post = PostModel.get.some_next(post.created_at, post.main_category)
        some_prew_post = PostModel.get.some_previous(post.created_at, post.main_category)

        context = {
            'post': post,
            'in_favorites': 'true' if request.user in post.wishlist.all() else 'false',
            'next_post': PostModel.get.next_(post.created_at, post.main_category),
            'prew_post': PostModel.get.previous(post.created_at, post.main_category),
            'some_next_prew_posts': some_prew_post + some_next_post,
            'family_categories': CategoryModel.objects.filter(posts_cat=post).first().get_family(),
        }
        return render(request, self.template_name, context)


class SearchPosts(View):

    template_name = 'search/search.html'
    posts_in_list = 50

    def get(self, request):
        search = request.GET.get('search', '')
        where = Q(name__icontains=search) | Q(name__istartswith=search)
        if len(search) > 4:
            where.add(Q(name__icontains=search[:-1]), Q.OR)
            where.add(Q(name__istartswith=search[:-1]), Q.OR)
        if len(search) > 6:
            where.add(Q(name__icontains=search[:-2]), Q.OR)
            where.add(Q(name__istartswith=search[:-2]), Q.OR)
        context = {
            'posts': PostModel.objects.filter(where, enabled=True).order_by('-created_at').distinct()[:self.posts_in_list]
        }
        return render(request, self.template_name, context)


def post_add_wishlist(request, pk):
    '''Добавляем пост в избранное'''

    if request.method == 'POST':
        try:
            post = PostModel.objects.get(pk=pk)
        except ObjectDoesNotExist:
            return JsonResponse({'ok': False}, safe=False)
        post.wishlist.add(request.user)
        post.save()
        return JsonResponse({'ok': True}, safe=False)
    return JsonResponse({'ok': False}, safe=False)


def post_remove_wishlist(request, pk):
    '''Удаляем пост из избранного'''

    if request.method == 'POST':
        try:
            post = PostModel.objects.get(pk=pk)
        except ObjectDoesNotExist:
            return JsonResponse({'ok': False}, safe=False)
        post.wishlist.remove(request.user)
        post.save()
        return JsonResponse({'ok': True}, safe=False)
    return JsonResponse({'ok': False}, safe=False)


def post_like(request, pk):
    '''Лайкнули пост'''

    if request.method == 'POST':
        try:
            post = PostModel.objects.get(pk=pk)
        except ObjectDoesNotExist:
            return JsonResponse({'ok': False}, safe=False)
        post.like = int(post.like) + 1
        post.save()
        return JsonResponse({'ok': True}, safe=False)
    return JsonResponse({'ok': False}, safe=False)

templates/sidebar/counters.html
<div class="card">
    <div class="card-header header-elements-inline">
        <h6 class="card-title">Всего на сайте</h6>
    </div>

    <div class="card-body">
        <div class="row text-center">
            <div class="col-6">
                <p><i class="icon-users2 icon-2x d-inline-block text-info"></i></p>
                <div class="h5 font-weight-semibold mb-0">{{ users_count }}</div>
                <span class="text-muted font-size-sm">Пользователей</span>
            </div>
            <div class="col-6">
                <p><i class="icon-images2 icon-2x d-inline-block text-warning"></i></p>
                <div class="h5 font-weight-semibold mb-0">{{ posts_count  }}</div>
                <span class="text-muted font-size-sm">
                    {% if app_step_drawing %}
                        Обучалок
                    {% else %}
                        Срисовок
                    {% endif %}
                </span>
            </div>
        </div>
    </div>
</div>

templates/sidebar/menu.html
{% load mptt_tags %}
<div class="card card-sidebar-mobile">
    <div class="card-header header-elements-inline">
        <h6 class="card-title">Меню {% if app_step_drawing %}обучалок{% else %}срисовок{% endif %}</h6>
        <div class="header-elements">
            <div class="list-icons">
                <a class="list-icons-item" data-action="collapse"></a>
            </div>
        </div>
    </div>

    <!-- Main navigation -->
    <div class="card-body p-0">
        <ul class="nav nav-sidebar" data-nav-type="accordion">

            {% recursetree categories_menu %}

            {% if not node.is_leaf_node %}
                <li class="nav-item nav-item-submenu">
                    <span class="nav-link cursor-pointer py-1">
                        {% if node.image_menu %}
                            <img src="{{ node.image_menu_path }}" alt="{{ node.get_alt }}" title="{{ node.get_title }}" class="w-35 mr-2">
                        {% else %}
                            <span class="w-35 mr-2"></span>
                        {% endif %}
                        <span class="mt-1">{{node}}</span>
                    </span>

                    {% if node.get_children %}

                    <ul class="nav nav-group-sub">
                        <li class="nav-item w-100p">
                            <a href="{{ node.get_absolute_url }}" class="nav-link text-uppercase py-1">
                                {% if node.image_menu %}
                                    <img src="{{ node.image_menu_path }}" alt="{{ node.get_alt }}" title="{{ node.get_title }}" class="w-35 mr-2">
                                {% else %}
                                    <span class="w-35 mr-2"></span>
                                {% endif %}
                                <span class="mt-1">Все срисовки {{node}}</span>
                            </a>
                        </li>

                        {% for child_two in node.get_children %}
                            <li class="nav-item">
                                <a href="{{child_two.get_absolute_url}}" class="nav-link py-1">
                                    {% if child_two.image_menu %}
                                        <img src="{{ child_two.image_menu_path }}" alt="{{ child_two.get_alt }}" title="{{ child_two.get_title }}" class="w-35 mr-2">
                                    {% else %}
                                        <span class="w-35 mr-2"></span>
                                    {% endif %}
                                    <span class="mt-1">{{child_two}}</span>
                                </a>
                            </li>
                        {% endfor %}

                    </ul>

                    {% endif %}
                </li>
            {% else %}
                <li class="nav-item">
                    <a href="{{ node.get_absolute_url }}" class="nav-link py-1">
                        {% if node.image_menu %}
                            <img src="{{ node.image_menu_path }}" alt="{{ node.get_alt }}" title="{{ node.get_title }}" class="w-35 mr-2">
                        {% else %}
                            <span class="width-35 mr-2"></span>
                        {% endif %}
                        <span class="mt-1">{{node}}</span>
                    </a>
                </li>
            {% endif %}

            {% endrecursetree %}

        </ul>
    </div>
    <!-- /main navigation -->

</div>

templates/sidebar/menu_profile.html
<div class="card card-sidebar-mobile">

    <!-- Header -->
    <div class="card-header header-elements-inline">
        <h6 class="card-title">Навигация</h6>
        <div class="header-elements">
            <div class="list-icons">
                <a class="list-icons-item" data-action="collapse"></a>
            </div>
        </div>
    </div>
    <!-- /header -->

    <!-- Main navigation -->
    <div class="card-body p-0">
        <ul class="nav nav-sidebar" data-nav-type="accordion">

            <li class="nav-item">
                <a href="{% url 'profile:detail' %}" class="nav-link">
                    <i class="icon-images3"></i>
                    <span> Мои картинки</span>
                </a>
            </li>
            <li class="nav-item">
                <a href="{% url 'profile:wishlist' %}" class="nav-link">
                    <i class="icon-heart5"></i>
                    <span> Избранное</span>
                </a>
            </li>
            <li class="nav-item">
                <a href="{% url 'profile:add_post' %}" class="nav-link">
                    <i class="icon-file-upload"></i>
                    <span> Загрузить картинку</span>
                </a>
            </li>
            <li class="nav-item">
                <a href="{% url 'profile:settings' %}" class="nav-link">
                    <i class="icon-cog5"></i>
                    <span> Настройки</span>
                </a>
            </li>
            <li class="nav-item-divider"></li>
            <li class="nav-item">
                <a href="{% url 'account_logout' %}" class="nav-link">
                    <i class="icon-switch2"></i>
                    <span> Выход</span>
                </a>
            </li>
        </ul>
    </div>
    <!-- /main navigation -->

</div>

templates/sidebar/post.html
<div class="card hover-posts">
    <a href="{{ post.get_absolute_url }}" class="card-body p-1">
        <div class="card-img-actions">
            {% if post.created_at|days_passed <= post_config.new_post_days %}
                <span class="badge bg-success-600 position-absolute position-badge-min rounded-circle badge-icon ml-1" title="Новая срисовка">
                    <i class="icon-new"></i>
                </span>
            {% endif %}
            {% if post.click >= post_config.post_popular %}
                <span class="badge bg-orange-600 position-absolute position-badge-min rounded-circle badge-icon ml-1" title="Самая посещаемая">
                    <i class="icon-eye-plus"></i>
                </span>
            {% endif %}
            {% if post.like >= post_config.post_best %}
                <span class="badge bg-danger-600 position-absolute position-badge-min rounded-circle badge-icon ml-1" title="Лучшая оценка">
                    <i class="icon-thumbs-up3"></i>
                </span>
            {% endif %}
            <img class="card-img img-fluid" src="{{ post.image_thumb_300.url }}" alt="{{ post.get_alt }}" title="{{ post.get_title }}">
        </div>
    </a>
    <h5 class="mb-3 px-1 mt-1 line-height-18 text-center">
        <a href="{{ post.get_absolute_url }}" class="font-weight-semibold text-default">{{ post|capfirst }}</a>
    </h5>
    <div class="card-footer py-2 px-3">
        <ul class="list-inline text-muted mb-3 mb-sm-0 d-sm-flex justify-content-sm-between align-items-sm-center">
            <li class="list-inline-item">
                <i class="icon-comment-discussion text-pink font-size-20" title="Комментарии"></i> {{ post.comments_post.count }} 
            </li>
            <li class="list-inline-item">
                <i class="icon-eye text-pink font-size-20" title="Просмотры"></i> {{post.click}}
            </li>
        </ul>
    </div>
</div>

templates/sidebar/sidebar.html
<div class="sidebar sidebar-light sidebar-main sidebar-sections sidebar-expand-md align-self-start">
    <div class="sidebar-mobile-toggler text-center">
        <a href="#" class="sidebar-mobile-main-toggle">
            <i class="icon-arrow-left8"></i>
        </a>
        <span class="font-weight-semibold">Основное меню</span>
        <a href="#" class="sidebar-mobile-expand">
            <i class="icon-screen-full"></i>
            <i class="icon-screen-normal"></i>
        </a>
    </div>

    <div class="sidebar-content">

        {% if user.is_authenticated %}
            {% include 'sidebar/user_profile.html' %}
        {% endif %}

        <!-- <div class="card">
            <div class="card-body">
                <div class="row text-center">
                    
                    {% if app_step_drawing %}
                        <a href="{% url 'front:home' %}">Перейти к срисовкам</a>
                    {% else %}
                        <a href="{% url 'step_drawing:home' %}">Перейти к обучалкам</a>
                    {% endif %}
                        
                </div>
            </div>
        </div> -->

        {% include 'sidebar/menu.html' %}
        {% include 'sidebar/counters.html' %}
        {% include 'sidebar/random_posts.html' %}
        <!-- {% include 'sidebar/users_online.html' %} -->

        {% if reklama_all.sidebar_reklama_block %}
        <div class="card sitebar_reklama mt-1">            
            <div class="card-body">
                {{ reklama_all.sidebar_reklama_block|safe }}
            </div>
        </div>
        {% endif %}

    </div>
</div>

templates/sidebar/sidebar_profile.html
<div class="sidebar sidebar-light sidebar-main sidebar-sections sidebar-expand-md align-self-start">

    <!-- Sidebar mobile toggler -->
    <div class="sidebar-mobile-toggler text-center">
        <a href="#" class="sidebar-mobile-main-toggle">
            <i class="icon-arrow-left8"></i>
        </a>
        <span class="font-weight-semibold">Меню срисовок</span>
        <a href="#" class="sidebar-mobile-expand">
            <i class="icon-screen-full"></i>
            <i class="icon-screen-normal"></i>
        </a>
    </div>
    <!-- /sidebar mobile toggler -->

    <!-- Sidebar content -->
    <div class="sidebar-content">

        {% if user.is_authenticated %}
            {% include 'sidebar/user_profile.html' %}
        {% endif %}

        <!-- <div class="card">
            <div class="card-body">
                <div class="row text-center">
                    <a href="{% url 'front:home' %}">Перейти к срисовкам</a>
                    <a href="{% url 'step_drawing:home' %}" class="mt-1">Перейти к обучалкам</a>
                </div>
            </div>
        </div> -->

        {% include 'sidebar/menu_profile.html' %}

    </div>
    <!-- /sidebar content -->
    
</div>

templates/sidebar/user_profile.html
<div class="card card-body {{ color }} text-center panel-bg">
    <div class="mb-3">
        <h5 class="mb-0 mt-1">{{ user }}</h5>
        <span class="d-block">Наш любимый пользователь</span>
    </div>

    <a href="{% url 'profile:detail' %}" class="d-inline-block mb-3">
        <img src="{{ user.get_avatar }}" class="rounded-round" width="110" height="110" alt="">
    </a>

    <ul class="list-inline mb-0">
        <li class="list-inline-item">
            <a href="{% url 'profile:detail' %}" title="Мои картинки" class="btn btn-outline btn-icon text-white btn-lg border-white rounded-round">
                <i class="icon-images3"></i>
            </a>
        </li>
        <li class="list-inline-item">
            <a href="{% url 'profile:wishlist' %}" title="Избранное" class="btn btn-outline btn-icon text-white btn-lg border-white rounded-round">
                <i class="icon-heart5"></i>
            </a>
        </li>
        <li class="list-inline-item">
            <a href="{% url 'profile:add_post' %}" title="Загрузить картинку" class="btn btn-outline btn-icon text-white btn-lg border-white rounded-round">
                <i class="icon-file-upload"></i>
            </a>
        </li>
    </ul>
</div>