api/urls.py
from rest_framework import routers

from api.posts.views import CategoryApiView
from api.front.views import WhatColorizeApiView
from api.comments.views import CommentsView

app_name = 'api'


router = routers.DefaultRouter()

router.register(r'what_colorize', WhatColorizeApiView, 'what_colorize')
router.register(r'category', CategoryApiView, 'category')
router.register(r'comments', CommentsView, 'comments')

urlpatterns = router.urls

front/urls.py
from django.urls import path

from front.views import Home, FeedBack, TermsOfUse,\
    RightHolders, Sitemap, CookieRules, WhatRegister, WhatColorize


app_name = 'front'

urlpatterns = [
    path('', Home.as_view(), name='home'),
    path('terms-of-use/', TermsOfUse.as_view(), name='terms_of_use'),
    path('feedback/', FeedBack.as_view(), name='feedback'),
    path('what-register/', WhatRegister.as_view(), name='what_register'),
    path('right-holders/', RightHolders.as_view(), name='right_holders'),
    path('cookie_rules/', CookieRules.as_view(), name='cookie_rules'),
    path('sitemap/', Sitemap.as_view(), name='sitemap'),
    path('what_colorize/', WhatColorize.as_view(), name='what_colorize'),
]

posts/urls.py
from django.urls import path
from posts.views import Category, Post, post_like,\
    post_add_wishlist, post_remove_wishlist, SearchPosts


app_name = 'posts'

urlpatterns = [
    path('post_like/<int:pk>/', post_like, name='post_like'),
    path('post_add_wishlist/<int:pk>/', post_add_wishlist, name='post_add_wishlist'),
    path('post_remove_wishlist/<int:pk>/', post_remove_wishlist, name='post_remove_wishlist'),
    path('search/', SearchPosts.as_view(), name='search'),

    # Эти 2 роута всегда внизу! они все съедают
    path('<slug:slug>/', Category.as_view(), name="category"),
    path('srisovka/<slug:slug>/', Post.as_view(), name="post")
]

users/urls.py
from django.urls import path
from users.views import Detail, Settings, Wishlist, UserAddPost

app_name = 'profile'


urlpatterns = [

    path('', Detail.as_view(), name='detail'),
    path('settings/', Settings.as_view(), name='settings'),
    path('wishlist/', Wishlist.as_view(), name='wishlist'),
    path('add_post/', UserAddPost.as_view(), name='add_post'),
]

templates/partials/footer.html
<a href="#top" type="button" class="scrollto btn btn-up bg-indigo-400 fab-menu-fixed fab-menu-bottom-right px-2" style="display: none;">
    <span>Вверх</span>
    <i class="icon-arrow-up13"></i>
</a>
<footer class="navbar navbar-expand-lg navbar-light pb-3 pt-2">
    <div class="col-md-6">
    <a href="{% url 'front:sitemap' %}" class="btn btn-link d-block text-left">
        <i class="icon-location3 mr-2"></i> Карта сайта
    </a>
    <a href="{% url 'front:feedback' %}" class="btn btn-link d-block text-left">
        <i class="icon-envelop3 mr-2"></i> Обратная связь
    </a>
    </div>
    <div class="col-md-6">
    <a href="{% url 'front:right_holders' %}" class="btn btn-link d-block text-left">
        <i class="icon-make-group mr-2"></i> Правообладателям
    </a>
    <a href="{% url 'front:terms_of_use' %}" class="btn btn-link d-block text-left">
        <i class="icon-make-group mr-2"></i> Условия использования
    </a>
    <a href="{% url 'front:cookie_rules' %}" class="btn btn-link d-block text-left">
        <i class="icon-make-group mr-2"></i> Политика использования файлов куки
    </a>
    </div>
</footer>

<div class="navbar navbar-expand-lg navbar-light">
<div class="navbar-collapse" id="navbar-footer">
    <span class="navbar-text">
    &copy; разработка веб-приложений <a href="https://Wstanley.ru" target="_blank">WStanley</a>
    </span>
    <ul class="navbar-nav ml-lg-auto">
    <li class="nav-item">
        <a href="/" class="navbar-nav-link">Картинки-для-срисовки.рф</a>
    </li>
    </ul>
</div>
</div>

templates/partials/header.html
<div class="page-header page-header-dark {{ color }}">

    <div class="page-header-content header-elements-md-inline">
        <div class="page-title d-flex">
            <a href="/" class="h2 text-white">Картинки для срисовки</a>
            <a href="#" class="header-elements-toggle text-white d-md-none"><i class="icon-more"></i></a>
            <a href="#" class="align-self-center sidebar-mobile-main-toggle text-white d-md-none"><i class="icon-paragraph-justify3"></i></a>
        </div>

        <div class="header-elements d-none bg-transparent py-0 border-0 mb-3 mb-md-0">
            <form action="{% url 'posts:search' %}" method="GET">
                <div class="form-group form-group-feedback form-group-feedback-right">
                    {% csrf_token %}
                    <input type="search" name="search" class="form-control text-white border-bottom-1 wmin-md-200" placeholder="Поиск срисовок">
                    <div class="form-control-feedback text-white">
                        <i class="icon-search4 font-size-sm"></i>
                    </div>
                </div>
            </form>
        </div>
    </div>

    <div class="navbar navbar-expand-md navbar-dark {{ color }} border-0 shadow-0">
        <div class="d-md-none w-100">
            <button type="button" class="navbar-toggler d-flex align-items-center w-100" data-toggle="collapse" data-target="#navbar-navigation">
                <i class="icon-menu-open mr-2"></i>
                Дополнительное меню
            </button>
        </div>
        <div class="navbar-collapse" id="navbar-navigation">
			<ul class="navbar-nav navbar-nav-highlight">

                <li class="nav-item nav-item-levels mega-menu-full">
					<a href="{% url 'front:what_colorize' %}" class="navbar-nav-link">
						<i class="icon-question3 mr-2"></i>
						Что нарисовать
					</a>
                </li>
				
				<li class="nav-item nav-item-levels mega-menu-full">
					<a href="https://xn----8sbafpvmb4ccfed.xn--p1ai/" class="navbar-nav-link" target="_blank">
						<i class="icon-images2 mr-2"></i>
						Все раскраски
					</a>
                </li>
            </ul>
        </div>
    </div>

    <ul class="fab-menu fab-menu-top-left d-none d-md-block" data-fab-toggle="click">
        <li>
            <button type="button" class="fab-menu-btn btn btn-light btn-float rounded-round btn-icon sidebar-control sidebar-main-toggle">
                <i class="icon-indent-decrease"></i>
            </button>
        </li>
    </ul>

    <ul class="fab-menu fab-menu-absolute fab-menu-top-right" data-fab-toggle="click">
        <li>
            <a class="fab-menu-btn btn bg-pink-300 btn-float rounded-round btn-icon">
                <i class="fab-icon-open icon-user"></i>
                <i class="fab-icon-close icon-cross2"></i>
            </a>

            <ul class="fab-menu-inner">
                {% if user.is_authenticated %}
                <li>
                    <div data-fab-label="Кабинет">
                        <a href="{% url 'profile:detail' %}" class="btn btn-light rounded-round btn-icon btn-float">
                            <i class="icon-user"></i>
                        </a>
                    </div>
                </li>
                <li>
                    <div data-fab-label="Выход">
                        <a href="{% url 'account_logout' %}" class="btn btn-light rounded-round btn-icon btn-float">
                            <i class="icon-exit"></i>
                        </a>
                    </div>
                </li>
                {% else %}
                <li>
                    <div data-fab-label="Вход">
                        <a href="{% url 'account_login' %}" class="btn btn-light rounded-round btn-icon btn-float">
                            <i class="icon-enter"></i>
                        </a>
                    </div>
                </li>
                <li>
                    <div data-fab-label="Регистрация">
                        <a href="{% url 'account_signup' %}" class="btn btn-light rounded-round btn-icon btn-float">
                            <i class="icon-plus3"></i>
                        </a>
                    </div>
                </li>
                <li>
                    <div data-fab-label="Зачем регистрироваться">
                        <a href="{% url 'front:what_register' %}" class="btn btn-light rounded-round btn-icon btn-float">
                            <i class="icon-question7"></i>
                        </a>
                    </div>
                </li>
                {% endif %}
            </ul>
        </li>
    </ul>
    
</div>