api/urls.py
from rest_framework import routers

from api.posts.views import CategoryApiView
from api.front.views import WhatColorizeApiView
from api.comments.views import CommentsView

app_name = 'api'


router = routers.DefaultRouter()

router.register(r'what_colorize', WhatColorizeApiView, 'what_colorize')
router.register(r'category', CategoryApiView, 'category')
router.register(r'comments', CommentsView, 'comments')

urlpatterns = router.urls

posts/urls.py
from django.urls import path
from posts.views import Category, Post, post_like,\
    post_add_wishlist, post_remove_wishlist, SearchPosts


app_name = 'posts'

urlpatterns = [
    path('post_like/<int:pk>/', post_like, name='post_like'),
    path('post_add_wishlist/<int:pk>/', post_add_wishlist, name='post_add_wishlist'),
    path('post_remove_wishlist/<int:pk>/', post_remove_wishlist, name='post_remove_wishlist'),
    path('search/', SearchPosts.as_view(), name='search'),

    # Эти 2 роута всегда внизу! они все съедают
    path('<slug:slug>/', Category.as_view(), name="category"),
    path('srisovka/<slug:slug>/', Post.as_view(), name="post")
]

step_drawing/models.py
from mptt.models import MPTTModel, TreeForeignKey, TreeManyToManyField
from ckeditor.fields import RichTextField
from imagekit.models import ImageSpecField
from imagekit.processors import ResizeToFill

from django.db import models
from django.urls import reverse
from django.conf import settings
from django.dispatch import receiver
from django.contrib.auth import get_user_model
from django.db.models.signals import pre_delete

from utils.file import get_extension
from utils.rand import get_random_number

User = get_user_model()


def image_path_category(instance, filename):
    return f'step_drawing_category/{str(instance.slug)}{get_extension(filename)}'

def image_menu_path_category(instance, filename):
    return f'step_drawing_category/{str(instance.slug)}_menu{get_extension(filename)}'


class CategoryStepDrawingModel(MPTTModel):

    class Meta:
        verbose_name = 'Категория пошаговое рисование'
        verbose_name_plural = 'Категории пошаговых рисований'
        db_table = 'step_category'

    class MPTTMeta:
        order_insertion_by = ['position']

    def __str__(self):
        return self.name

    parent = TreeForeignKey('self', on_delete=models.CASCADE, null=True, blank=True, related_name='children')

    name = models.CharField(max_length=100, unique=True, verbose_name='Наименование')
    position = models.IntegerField(default=0, verbose_name='Позиция')
    enabled = models.BooleanField(default=False, choices=settings.STATUS_CHOICES,
        verbose_name='Включено', help_text='Отображать/неотображать категорию')
    text1 = RichTextField(null=True, blank=True, verbose_name='Текст 1')
    text2 = RichTextField(null=True, blank=True, verbose_name='Текст 2')

    h1 = models.CharField(max_length=250)
    title = models.CharField(max_length=250, default='Картинки для срисовки')
    slug = models.SlugField(max_length=100, unique=True, verbose_name='Url(slug)', help_text='Ссылка на категорию')
    description = models.TextField(null=True, blank=True)

    image = models.FileField(upload_to=image_path_category, null=True, blank=True, verbose_name='Осносное изображение')
    image_menu = models.FileField(upload_to=image_menu_path_category, null=True, blank=True,
        verbose_name='Картинка в меню', help_text='Иконка в меню')
    show_main = models.BooleanField(default=False, verbose_name='Отображать на главной или нет')

    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Создано')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='Обновлено')

    def image_path(self):
        return f'{settings.MEDIA_URL}{self.image}'

    def image_menu_path(self):
        return f'{settings.MEDIA_URL}{self.image_menu}'

    def get_alt(self):
        return f'альт картинки'

    def get_title(self):
        return f'Ститле картинке'

    def get_absolute_url(self):
        return reverse('step_drawing:category_or_post', args=[str(self.slug)])


def image_path_post(instance, filename):
    '''Фомируем путь загрузки картинки поста'''
    return f'step_drawing_posts/{str(instance.slug)}{get_extension(filename)}'


class PostStepDrawingModel(models.Model):

    class Meta:
        verbose_name = 'Запись пошаговое рисование'
        verbose_name_plural = 'Записи пошаговое рисование'
        db_table = 'step_posts'
        ordering = ['-created_at']

    def __str__(self):
        return self.name

    wishlist = models.ManyToManyField(User)

    position = models.IntegerField(default=0, verbose_name='Позиция')
    enabled = models.BooleanField(
        default=False,
        choices=settings.STATUS_CHOICES,
        verbose_name='Опубликовано',
        help_text='Отображать/неотображать пост'
    )
    categories = TreeManyToManyField(
        CategoryStepDrawingModel,
        verbose_name='Категории',
        related_name='posts_cat',
        blank=True
    )
    main_category = TreeForeignKey(
        CategoryStepDrawingModel,
        on_delete=models.CASCADE,
        null=True,
        verbose_name='Основная категория',
        related_name='posts_main',
        help_text='Используется для хлебных крошек'
    )

    name = models.CharField(max_length=250, unique=True, verbose_name='h1', help_text='Название поста')
    slug = models.SlugField(max_length=100, unique=True, verbose_name='Url(slug)')
    title = models.CharField(max_length=250, default='Картинка для срисовки')
    description = models.TextField(null=True, blank=True)

    text = RichTextField(null=True, blank=True, verbose_name='Текст')

    show_main = models.BooleanField(default=False, verbose_name='Отображать на главной или нет')
    execution_time = models.CharField(max_length=50, verbose_name='Время на выполнения', null=True, blank=True)
    level = models.CharField(max_length=100, verbose_name='Уровень сложности', choices=settings.LEVEL_CHOICES)

    image = models.ImageField(
        upload_to=image_path_post,
        verbose_name='Основное изображение',
        help_text='Отображаестя в категории'
    )
    image_thumb_300 = ImageSpecField(
        source='image',
        processors=[ResizeToFill(300, 225)],
        format='JPEG', options={'quality': 65}
    )
    image_thumb_200 = ImageSpecField(
        source='image',
        processors=[ResizeToFill(200, 150)],
        format='JPEG', options={'quality': 60}
    )

    like = models.IntegerField(default=0, verbose_name='Лайки', help_text='Общее количество лайков')
    click = models.IntegerField(default=0, verbose_name='Клики', help_text='Общее количество кликов')

    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Создано')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='Обновлено')

    def save(self, *args, **kwargs):
        if not self.id:
            self.like = get_random_number(0, 3)
            self.click = get_random_number(0, 6)
        super(PostStepDrawingModel, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('step_drawing:category_or_post', args=[str(self.slug)])

    def image_path(self):
        return f'{settings.MEDIA_URL}{self.image}'


def images_path_post(instance, filename):
    '''Фомируем путь загрузки картинки поста'''
    return f'step_drawing_posts/{str(instance.post.slug)}{get_extension(filename)}'


class VideoPostModel(models.Model):

    class Meta:
        verbose_name = 'Видео для поста обучения'
        verbose_name_plural = 'Видео для поста обучения'
        db_table = 'step_videos'

    def __str__(self):
        return f'Видео для {self.post}'

    post = models.ForeignKey('PostStepDrawingModel', related_name='videos', on_delete=models.CASCADE)

    frame = models.CharField(max_length=350, verbose_name='Видео')
    name = models.CharField(max_length=250, verbose_name='Название')


class ImagesPostDrawingModel(models.Model):

    class Meta:
        verbose_name = 'Изображение для постов пошагового рисования'
        verbose_name_plural = 'Изображения для постов пошагового рисования'
        db_table = 'step_images'
        ordering = ['position']

    def __str__(self):
        return f'{self.steps} для {self.post}'

    position = models.IntegerField(default=0, verbose_name='Сортировка')
    steps = models.CharField(max_length=30, verbose_name='Шаг/Этап')

    post = models.ForeignKey('PostStepDrawingModel', related_name='images', on_delete=models.CASCADE)

    text_up = RichTextField(null=True, blank=True, verbose_name='Текст сверху')
    text_down = RichTextField(null=True, blank=True, verbose_name='Текст внизу')

    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Создано')

    image = models.FileField(
        upload_to=images_path_post,
        null=True, blank=True,
        verbose_name='Изображение',
    )
    image_thumb_300 = ImageSpecField(
        source='image',
        processors=[ResizeToFill(300, 225)],
        format='JPEG', options={'quality': 65}
    )
    image_thumb_200 = ImageSpecField(
        source='image',
        processors=[ResizeToFill(200, 150)],
        format='JPEG', options={'quality': 60}
    )

    def image_path(self):
        return f'{settings.MEDIA_URL}{self.image}'



@receiver(pre_delete, sender=ImagesPostDrawingModel)
def image_posts_delete(sender, instance, **kwargs):
    '''Удаляем картинки с постов, при удалении поста'''
    if instance.image:
        instance.image.delete()


@receiver(pre_delete, sender=PostStepDrawingModel)
def posts_im_delete(sender, instance, **kwargs):
    '''Удаляем картинки с постов, при удалении поста'''
    if instance.image:
        instance.image.delete()


@receiver(pre_delete, sender=CategoryStepDrawingModel)
def cat_image_delete(sender, instance, **kwargs):
    '''Удаляем картинки с категории, при удалении категории'''
    if instance.image:
        instance.image.delete()
    if instance.image_menu:
        instance.image_menu.delete()

api/posts/views.py
from rest_framework import mixins, viewsets
from rest_framework.permissions import AllowAny

from api.posts.serializers import CategorySerializer
from posts.models import Category


class CategoryApiView(mixins.ListModelMixin, viewsets.GenericViewSet):

    serializer_class = CategorySerializer

    def get_queryset(self):
        first_level = self.request.GET.get('first_level', None)
        if first_level:
            return Category.objects.filter(level=0)
        return Category.objects.all()

    def get_permissions(self):
        permission_classes = [AllowAny, ]
        return [permission() for permission in permission_classes]

posts/views.py
from django.http import JsonResponse, Http404
from django.db.models import Q
from django.shortcuts import render
from django.views.generic import View
from django.core.paginator import Paginator
from django.core.exceptions import ObjectDoesNotExist

from posts.models import Category as CategoryModel, Post as PostModel


class Category(View):

    template_name = 'category/category.html'

    first_page = 1
    posts_in_page = 34

    def get(self,request, slug):
        categories = CategoryModel.objects.filter(slug=slug).get_descendants(include_self=True)
        if categories:
            active_page = request.GET.get('page', self.first_page)
            posts = PostModel.objects.filter(categories__slug=slug, enabled=True).order_by('main_category__position', '-created_at')
            p = Paginator(posts, self.posts_in_page)
            page = p.page(active_page)
            context = {
                'category': categories.first(),
                'categories': categories,
                'posts': page.object_list,
                'page_range': p.page_range,
                'active_page': active_page,
                'page': page
            }
            return render(request, self.template_name, context)
        raise Http404()


class Post(View):

    template_name = 'post/post.html'

    def get(self, request, slug):
        try:
            post = PostModel.objects.get(slug=slug)
        except ObjectDoesNotExist:
            raise Http404()

        post.click = int(post.click) + 1
        post.save()

        some_next_post = PostModel.get.some_next(post.created_at, post.main_category)
        some_prew_post = PostModel.get.some_previous(post.created_at, post.main_category)

        context = {
            'post': post,
            'in_favorites': 'true' if request.user in post.wishlist.all() else 'false',
            'next_post': PostModel.get.next_(post.created_at, post.main_category),
            'prew_post': PostModel.get.previous(post.created_at, post.main_category),
            'some_next_prew_posts': some_prew_post + some_next_post,
            'family_categories': CategoryModel.objects.filter(posts_cat=post).first().get_family(),
        }
        return render(request, self.template_name, context)


class SearchPosts(View):

    template_name = 'search/search.html'
    posts_in_list = 50

    def get(self, request):
        search = request.GET.get('search', '')
        where = Q(name__icontains=search) | Q(name__istartswith=search)
        if len(search) > 4:
            where.add(Q(name__icontains=search[:-1]), Q.OR)
            where.add(Q(name__istartswith=search[:-1]), Q.OR)
        if len(search) > 6:
            where.add(Q(name__icontains=search[:-2]), Q.OR)
            where.add(Q(name__istartswith=search[:-2]), Q.OR)
        context = {
            'posts': PostModel.objects.filter(where, enabled=True).order_by('-created_at').distinct()[:self.posts_in_list]
        }
        return render(request, self.template_name, context)


def post_add_wishlist(request, pk):
    '''Добавляем пост в избранное'''

    if request.method == 'POST':
        try:
            post = PostModel.objects.get(pk=pk)
        except ObjectDoesNotExist:
            return JsonResponse({'ok': False}, safe=False)
        post.wishlist.add(request.user)
        post.save()
        return JsonResponse({'ok': True}, safe=False)
    return JsonResponse({'ok': False}, safe=False)


def post_remove_wishlist(request, pk):
    '''Удаляем пост из избранного'''

    if request.method == 'POST':
        try:
            post = PostModel.objects.get(pk=pk)
        except ObjectDoesNotExist:
            return JsonResponse({'ok': False}, safe=False)
        post.wishlist.remove(request.user)
        post.save()
        return JsonResponse({'ok': True}, safe=False)
    return JsonResponse({'ok': False}, safe=False)


def post_like(request, pk):
    '''Лайкнули пост'''

    if request.method == 'POST':
        try:
            post = PostModel.objects.get(pk=pk)
        except ObjectDoesNotExist:
            return JsonResponse({'ok': False}, safe=False)
        post.like = int(post.like) + 1
        post.save()
        return JsonResponse({'ok': True}, safe=False)
    return JsonResponse({'ok': False}, safe=False)

templates/post_step/icons_block.html
<div class="row text-center">
    {% if post.videos.count %}
        <div class="col-3 pb-2 pt-3">
            <i class="icon-hour-glass2 icon-2x"></i>
            <p class="mt-3">{{ post.execution_time }}</p>
        </div>
        <div class="col-3 pb-2 pt-3">
            <i class="icon-list-numbered icon-2x"></i>
            <p class="mt-3">{{ post.images.count }} шаг{{ post.images.count|rupluralize:",а,ов" }}</p>
        </div>
        <div class="col-3 pb-2 pt-3">
            <i class="icon-stats-bars2 icon-2x"></i>
            <p class="mt-3">{{ post.get_level_display }}</p>
        </div>
        <div class="col-3 pb-2 pt-3">
            <i class="icon-youtube icon-2x"></i>
            <p class="mt-3">Есть видео</p>
        </div>
    {% else %}
        <div class="col-4 pb-2 pt-3">
            <i class="icon-hour-glass2 icon-2x"></i>
            <p class="mt-3">{{ post.execution_time }}</p>
        </div>
        <div class="col-4 pb-2 pt-3">
            <i class="icon-list-numbered icon-2x"></i>
            <p class="mt-3">{{ post.images.count }} шаг{{ post.images.count|rupluralize:",а,ов" }}</p>
        </div>
        <div class="col-4 pb-2 pt-3">
            <i class="icon-stats-bars2 icon-2x"></i>
            <p class="mt-3">{{ post.get_level_display }}</p>
        </div>
    {% endif %}
</div>

templates/post_step/post.html
{% extends "base.html" %}
{% load solo_tags %}
{% load matem %}

{% block css %}<link href="{% static 'css/category_step_drawing.css' %}" rel="stylesheet" type="text/css">{% endblock css %}
{% block js %}<script src="{% static 'js/category_step_drawing.js' %}"></script>{% endblock js %}
{% block title %}{{post.title|safe}}{% endblock %}
{% block description %}{{post.description|safe}}{% endblock %}
{% block opgraph %}
    <meta property="og:site_name" content="https://картинки-для-срисовки.рф/"/>
    <meta property="og:title" content="{{post.title|safe}}"/>
    <meta property="og:description" content="{{post.description|safe}}"/>
    <meta property="og:image" content="https://картинки-для-срисовки.рф{{post.image_path}}"/>
    <meta property="og:image:type" content="image/jpeg" />
    <meta property="og:type" content="website"/>
    <meta property="og:url" content= "https://картинки-для-срисовки.рф{{post.get_absolute_url}}" />
{% endblock opgraph %}

{% block content %}
{% get_solo 'configs.ReklamaStepPosts' as reklama_step_post %}
	<div class="page-content">

        {% include 'sidebar/sidebar.html' %}

        <div class="content-wrapper">
			<div class="content" id="app">

                {% include 'post/breadcrumb.html' %}

                {% if reklama_all.top_reklama_block %}                    
                    <div class="card">
                        <div class="card-body">
                            {{ reklama_all.top_reklama_block|safe }}
                        </div>
                    </div>
                {% endif %}

                <div class="card">
                    <div class="card-header header-elements-inline">
                        <h1>{{ post }}</h1>
                    </div>
                    <div class="card-body">
                        {{ post.text|safe }}
                    </div>
                </div>

                <div class="card">
                    <div class="card-body">
                        {% include 'post_step/icons_block.html' %}
                    </div>
                </div>

                <div class="card">
                    <div class="card-body">
                        <div class="text-center">
                            <img class="img-fluid" src="{{ post.image_path }}" alt="">
                        </div>
                    </div>
                </div>

                {% include 'post_step/steps.html' %}

                {% include 'post_step/videos.html' %}

            </div>
        </div>
    </div>
{% endblock %}

templates/post_step/steps.html
{% for step in post.images.all %}
    <div class="card" id="step{{ forloop.counter }}">
        <div class="card-header">
            <h2 class="card-title font-weight-semibold">{{ step.steps }}</h2>
        </div>
        <div class="card-body">
            {{ step.text_up|safe }}
            <div class="card-img-actions text-center mb-2">
                <img class="img-fluid" src="{{ step.image_thumb_300.url }}" alt="">
                <div class="card-img-actions-overlay card-img m-auto">
                    <a href="{{ step.image_path  }}" class="btn btn-outline bg-white text-white border-white border-2 btn-icon rounded-round" data-popup="lightbox">
                        <i class="icon-plus3"></i>
                    </a>

                </div>
            </div>
            {{ step.text_down|safe }}
        </div>
        <div class="card-footer bg-transparent d-sm-flex justify-content-sm-between align-items-sm-center border-top-0 pt-0 pb-3">
            {% if forloop.first %}
                <span></span>
            {% else %}
                <a href="#step{{ forloop.counter0 }}" class="scrollto"><i class="icon-circle-left2 mr-2"></i> Предыдущий шаг</a>
            {% endif %}

            {% if post.videos.count and not forloop.last %}
                <a href="#step_video" class="scrollto">Перейти к видео <i class="icon-youtube ml-2"></i></a>
            {% endif %}

            {% if not forloop.last %}
                <a href="#step{{ forloop.counter|plus1 }}" class="scrollto">Следующий шаг <i class="icon-circle-right2 ml-2"></i></a>
            {% endif %}
        </div>
    </div>
{% endfor %}
    

templates/post_step/videos.html
<span id="step_video"></span>
{% for one_video in post.videos.all %}
<div class="card">
    <div class="card-header">
        <h3 class="card-title font-weight-semibold">{{ one_video.name }}</h3>
    </div>
    <div class="card-body">
        <div class="card-img embed-responsive embed-responsive-16by9 mb-3">
            {{ one_video.frame|safe }}
        </div>
    </div>
</div>
{% endfor %}